// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnumDefine.proto

#ifndef PROTOBUF_INCLUDED_EnumDefine_2eproto
#define PROTOBUF_INCLUDED_EnumDefine_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_util.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_EnumDefine_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_EnumDefine_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

enum EAppStatusType {
  EAppStatusInit = 1,
  EAppStatusStartup = 2,
  EAppStatusWebsocketInit = 3,
  EAppStatusWebsocketConnected = 4,
  EAppStatusWebsocketJoin = 5,
  EAppStatusWebsocketProduce = 6,
  EAppStatusWebsocketVideoPause = 7,
  EAppStatusWebsocketVideoResume = 8,
  EAppStatusWebsocketDestroy = 9,
  EAppStatusDestroy = 10
};
bool EAppStatusType_IsValid(int value);
const EAppStatusType EAppStatusType_MIN = EAppStatusInit;
const EAppStatusType EAppStatusType_MAX = EAppStatusDestroy;
const int EAppStatusType_ARRAYSIZE = EAppStatusType_MAX + 1;

enum ECameraStatusType {
  ECameraNone = 0,
  ECameraRuning = 1
};
bool ECameraStatusType_IsValid(int value);
const ECameraStatusType ECameraStatusType_MIN = ECameraNone;
const ECameraStatusType ECameraStatusType_MAX = ECameraRuning;
const int ECameraStatusType_ARRAYSIZE = ECameraStatusType_MAX + 1;

enum ESplitMethod {
  ELeftRightSplit = 0,
  EUpperLowerSplit = 1
};
bool ESplitMethod_IsValid(int value);
const ESplitMethod ESplitMethod_MIN = ELeftRightSplit;
const ESplitMethod ESplitMethod_MAX = EUpperLowerSplit;
const int ESplitMethod_ARRAYSIZE = ESplitMethod_MAX + 1;

// ===================================================================


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::EAppStatusType> : ::std::true_type {};
template <> struct is_proto_enum< ::ECameraStatusType> : ::std::true_type {};
template <> struct is_proto_enum< ::ESplitMethod> : ::std::true_type {};

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_EnumDefine_2eproto
